INSERT INTO product VALUES
(1, 'No Longer Human (Ningen Shikkaku)', 'Osamu Dazai', 'New Directions Publishing', '1958', '0811204812', '["Autobiographical Fiction", "Psychological"]', 196, 'English', 'epub', '/covers/no-longer-human.jpg', '/No Longer Human.epub', 'No Longer Human by Osamu Dazai is a deeply introspective novel that delves into the life of Ōba Yōzō, a man who feels profoundly disconnected from society and struggles with his sense of identity. The story is presented through a series of notebooks written by Yōzō, chronicling his experiences from childhood to adulthood.\n

Yōzō is depicted as an outsider, unable to understand or fit in with the norms and expectations of those around him. His life is marked by a series of failed relationships, bouts of depression, and substance abuse. He often uses humor and a facade of cheerfulness to mask his inner turmoil, but this only deepens his sense of alienation.\n

Throughout the novel, Yōzō grapples with feelings of shame, guilt, and existential despair. His attempts to find solace through art, love, and friendship are ultimately unsuccessful, leading him to a life of isolation and self-destruction.\n

"No Longer Human" is a poignant exploration of the human psyche, capturing the profound loneliness and existential angst of its protagonist. It is considered one of the most significant works by Dazai, and a powerful commentary on the struggle for identity and the meaning of existence.', 11.95, 1.95, 4.5, 0, 10),
(2, 'All Quiet On The Western Front', 'Erich Maria Remerque', 'Ballantine Books', '1930', '0449213943', '["War Fiction", "Historical"]', 141, 'English', 'epub', '/covers/all-quiet-on-the-western-front.jpg', '/All Quiet On The Western Front.epub', '"All Quiet on the Western Front" is a novel by Erich Maria Remarque that provides a harrowing and realistic portrayal of a soldier and his life during World War I. The story is narrated by Paul Bäumer, a young German soldier who enlists in the army with his classmates, driven by patriotic fervor instilled by their teacher.

As the novel progresses, Paul and his comrades experience the brutal realities of war. The romanticized ideals of heroism and honor quickly fade away as they face the horrors of trench warfare, constant bombardments, and the pervasive presence of death. Paul witnesses the physical and psychological toll the war takes on his fellow soldiers, many of whom are killed or severely wounded.

Throughout the novel, Remarque vividly depicts the dehumanizing effects of war, highlighting the loss of innocence and the profound sense of disillusionment felt by the soldiers. Paul struggles to find meaning in the senseless violence and grapples with feelings of alienation when he returns home on leave, finding it impossible to relate to the civilians who cannot comprehend the true nature of the front lines.', 6.99, 0.0, 4.5, 0, 10),
(3, 'The Road', 'Cormac McCarthy', 'Vintage', '2006', '0307387895', '["Fiction", "Dystopian", "Survival"]', 287, 'English', 'epub', '/covers/the-road.jpg', '/The Road.epub', '"The Road" by Cormac McCarthy is a bleak and harrowing tale set in a post-apocalyptic world. The story follows an unnamed man and his young son as they journey through a desolate landscape, struggling to survive in the aftermath of an unspecified catastrophe that has decimated civilization and the natural environment.\n

The father and son push a shopping cart filled with their meager belongings, constantly on the move to avoid the dangers that lurk in this ravaged world. They face numerous challenges, including scarcity of food and clean water, harsh weather conditions, and the threat of violent encounters with other survivors who have turned to cannibalism.\n

As they travel, the father is determined to protect his son and keep the flame of hope alive, even as he himself is slowly succumbing to illness. The boy, innocent and compassionate, serves as a beacon of hope and humanity, often questioning the moral choices they must make to survive.\n

The stark and minimalist prose emphasizes the bleakness of the world they inhabit, creating a powerful atmosphere of despair and desolation. Despite the grim setting, the novel is ultimately a story of love, resilience, and the bond between father and son.\n

The narrative reaches its climax as the father nears death, leaving the boy to face the world alone. However, the novel ends on a note of cautious optimism, suggesting that the boy may find safety and continue to carry the metaphorical "fire" of hope and goodness in a world that has lost its way.', 9.99, 0.99, 4.1, 0, 10),
(4, 'Kokoro', 'Soseki Natsume', 'Penguin Classics', '2010', '1101195819', '["Fiction", "Psychological"]', 272, 'English', 'pdf', '/covers/kokoro.jpg', '/Kokoro.pdf', '"Kokoro" by Natsume Sōseki is a profound exploration of the complexities of human relationships and the inner workings of the human mind. The novel, set in early 20th-century Japan, is divided into three parts and primarily focuses on the relationship between a young man (referred to as the narrator) and an older man he calls Sensei.\n

The story begins with the narrator, a university student, meeting and becoming intrigued by Sensei, a reclusive and enigmatic man. As their friendship develops, the narrator seeks to understand the reasons behind Sensei withdrawn demeanor and the profound sadness that seems to envelop him. Sensei, however, remains guarded about his past and his personal struggles.\n

In the second part, the narrator returns to his family home after the illness of his father. During this time, he continues to reflect on his interactions with Sensei and the lessons he has learned from him. His influence begins to shape the narrators views on life and relationships.\n

The final part of the novel reveals a long letter to the narrator, in which he confesses the events of his past that have led to his present state of despair. He recounts his friendship with a man named K, their rivalry for the affections of a woman, and the resulting betrayal that culminated in the tragic death of K. The guilt and remorse over these events have haunted him ever since, leading to his self-imposed isolation.\n

"Kokoro" delves deeply into themes of loneliness, guilt, and the search for meaning in a rapidly changing society. Through the introspective and poignant narrative, Sōseki captures the essence of the human condition, making "Kokoro" a timeless and influential work in Japanese literature.', 2.99, 0.0, 4.3, 0, 10),
(5, 'Meditations', 'Marcus Auerlius', 'Penguin UK', '2006', '0140449337', '["Philosphy", "Self-help", "Autobiography"]', 433, 'English', 'pdf', '/covers/meditations.jpg', '/Meditations.pdf', 'Meditations by Marcus Aurelius is a collection of personal writings and reflections by the Roman Emperor, providing insights into Stoic philosophy and his thoughts on life, duty, and virtue. Written as a series of notes to himself, the work explores themes such as the importance of rationality, self-discipline, and the transient nature of existence. It serves as a guide to personal improvement and ethical living, emphasizing inner peace and resilience in the face of adversity. The text remains a significant source of philosophical guidance and inspiration.', 8.99, 0.99, 4.8, 0, 10),
(6, 'Atomic Habits', 'James Clear', 'Penguin Publishing Group', '2018', 'B07D23CFGR', '["Self-Help"]', 291, 'English', 'pdf', '/covers/atomic-habits.jpg', '/Atomic Habits.pdf', '"Atomic Habits" by James Clear is a self-help book that explores the science behind habit formation and provides practical strategies for building good habits and breaking bad ones. Clear argues that small changes, or "atomic habits," can lead to remarkable results over time. He introduces the concept of the "habit loop" and explains how habits are formed, maintained, and changed.\m

The book offers a comprehensive framework for habit formation, focusing on four key principles: making habits obvious, attractive, easy, and satisfying. Clear provides actionable advice on how to apply these principles to various areas of life, such as health, productivity, and relationships. He emphasizes the importance of setting clear goals, tracking progress, and creating an environment conducive to habit formation.\m

Through real-life examples, scientific research, and practical exercises, "Atomic Habits" offers readers a roadmap for transforming their habits and achieving their goals. It encourages readers to focus on continuous improvement and to harness the power of small changes to create lasting positive change in their lives.', 1.99, 0.0, 4.9, 0, 10),
(7, 'Sapiens', 'Yuval N. Harari', 'Signal Books', '2014', '0771038526', '["Non-Fiction", "Anthropology", "Science"]', 443, 'English', 'pdf', '/covers/sapiens.jpg', '/Sapiens.pdf', '"Sapiens: A Brief History of Humankind" by Yuval Noah Harari is a sweeping historical narrative that explores the origins and evolution of Homo sapiens, from the emergence of our species in Africa to the present day. Harari examines key milestones in human history, including the Cognitive Revolution, the Agricultural Revolution, the development of complex societies, and the rise of empires and civilizations.\n

The book offers a thought-provoking analysis of how humans have shaped the world around them and been shaped by it in return. Harari challenges conventional wisdom and offers fresh perspectives on topics such as the rise of religion, the spread of agriculture, and the impact of technology on society.\n

Through engaging storytelling and rigorous research, "Sapiens" invites readers to reconsider their understanding of human history and to reflect on the future of our species. The insightful commentary prompts readers to ponder questions about identity, progress, and the meaning of life in the modern world.', 9.99, 1.00, 4.7, 0, 10),
(8, '1984', 'George Orwell', 'Buccaneer Books', '1949', '0899663680', '["Fiction", "Dystopian"]', 309, 'English', 'pdf', '/covers/1984.jpg', '/1984.pdf', '1984 by George Orwell is a dystopian novel set in a totalitarian society where the government, led by the Party and its leader Big Brother, exercises complete control over every aspect of citizens&apos; lives. The story follows Winston Smith, an employee of the Party&apos;s Ministry of Truth, who becomes disillusioned with the oppressive regime and begins to rebel against it.\n

In the world of 1984, individuality is suppressed, truth is manipulated, and dissent is brutally punished. The Party employs surveillance, propaganda, and thought control to maintain its grip on power, creating a climate of fear and suspicion among the populace.\n

As Winston embarks on a journey of resistance, he forms a forbidden relationship with Julia, a fellow Party member, and begins to question the reality of the world around him. However, their rebellion against the Party comes at great personal risk, and they soon find themselves ensnared in a web of betrayal and deceit.', 7.99, 1.99, 4.5, 0, 10)