INSERT INTO product VALUES
(1, 'No Longer Human (Ningen Shikkaku)', 'Osamu Dazai', 'New Directions Publishing', '1958', '0811204812', '["Autobiographical Fiction", "Psychological"]', 196, 'English', 'epub', '/covers/no-longer-human.jpg', '/No Longer Human.epub', 'No Longer Human by Osamu Dazai is a deeply introspective novel that delves into the life of Ōba Yōzō, a man who feels profoundly disconnected from society and struggles with his sense of identity. The story is presented through a series of notebooks written by Yōzō, chronicling his experiences from childhood to adulthood.\n

Yōzō is depicted as an outsider, unable to understand or fit in with the norms and expectations of those around him. His life is marked by a series of failed relationships, bouts of depression, and substance abuse. He often uses humor and a facade of cheerfulness to mask his inner turmoil, but this only deepens his sense of alienation.\n

Throughout the novel, Yōzō grapples with feelings of shame, guilt, and existential despair. His attempts to find solace through art, love, and friendship are ultimately unsuccessful, leading him to a life of isolation and self-destruction.\n

"No Longer Human" is a poignant exploration of the human psyche, capturing the profound loneliness and existential angst of its protagonist. It is considered one of the most significant works by Dazai, and a powerful commentary on the struggle for identity and the meaning of existence.', 11.95, 1.95, 4.5, 0, 10),
(2, 'All Quiet On The Western Front', 'Erich Maria Remerque', 'Ballantine Books', '1930', '0449213943', '["War Fiction", "Historical"]', 141, 'English', 'epub', '/covers/all-quiet-on-the-western-front.jpg', '/All Quiet On The Western Front.epub', '"All Quiet on the Western Front" is a novel by Erich Maria Remarque that provides a harrowing and realistic portrayal of a soldier and his life during World War I. The story is narrated by Paul Bäumer, a young German soldier who enlists in the army with his classmates, driven by patriotic fervor instilled by their teacher.

As the novel progresses, Paul and his comrades experience the brutal realities of war. The romanticized ideals of heroism and honor quickly fade away as they face the horrors of trench warfare, constant bombardments, and the pervasive presence of death. Paul witnesses the physical and psychological toll the war takes on his fellow soldiers, many of whom are killed or severely wounded.

Throughout the novel, Remarque vividly depicts the dehumanizing effects of war, highlighting the loss of innocence and the profound sense of disillusionment felt by the soldiers. Paul struggles to find meaning in the senseless violence and grapples with feelings of alienation when he returns home on leave, finding it impossible to relate to the civilians who cannot comprehend the true nature of the front lines.', 6.99, 0.0, 4.5, 0, 10),
(3, 'The Road', 'Cormac McCarthy', 'Vintage', '2006', '0307387895', '["Fiction", "Dystopian", "Survival"]', 287, 'English', 'epub', '/covers/the-road.jpg', '/The Road.epub', '"The Road" by Cormac McCarthy is a bleak and harrowing tale set in a post-apocalyptic world. The story follows an unnamed man and his young son as they journey through a desolate landscape, struggling to survive in the aftermath of an unspecified catastrophe that has decimated civilization and the natural environment.\n

The father and son push a shopping cart filled with their meager belongings, constantly on the move to avoid the dangers that lurk in this ravaged world. They face numerous challenges, including scarcity of food and clean water, harsh weather conditions, and the threat of violent encounters with other survivors who have turned to cannibalism.\n

As they travel, the father is determined to protect his son and keep the flame of hope alive, even as he himself is slowly succumbing to illness. The boy, innocent and compassionate, serves as a beacon of hope and humanity, often questioning the moral choices they must make to survive.\n

The stark and minimalist prose emphasizes the bleakness of the world they inhabit, creating a powerful atmosphere of despair and desolation. Despite the grim setting, the novel is ultimately a story of love, resilience, and the bond between father and son.\n

The narrative reaches its climax as the father nears death, leaving the boy to face the world alone. However, the novel ends on a note of cautious optimism, suggesting that the boy may find safety and continue to carry the metaphorical "fire" of hope and goodness in a world that has lost its way.', 9.99, 0.99, 4.1, 0, 10),
(4, 'Kokoro', 'Soseki Natsume', 'Penguin Classics', '2010', '1101195819', '["Fiction", "Psychological"]', 272, 'English', 'pdf', '/covers/kokoro.jpg', '/Kokoro.pdf', '"Kokoro" by Natsume Sōseki is a profound exploration of the complexities of human relationships and the inner workings of the human mind. The novel, set in early 20th-century Japan, is divided into three parts and primarily focuses on the relationship between a young man (referred to as the narrator) and an older man he calls Sensei.\n

The story begins with the narrator, a university student, meeting and becoming intrigued by Sensei, a reclusive and enigmatic man. As their friendship develops, the narrator seeks to understand the reasons behind Sensei withdrawn demeanor and the profound sadness that seems to envelop him. Sensei, however, remains guarded about his past and his personal struggles.\n

In the second part, the narrator returns to his family home after the illness of his father. During this time, he continues to reflect on his interactions with Sensei and the lessons he has learned from him. His influence begins to shape the narrators views on life and relationships.\n

The final part of the novel reveals a long letter to the narrator, in which he confesses the events of his past that have led to his present state of despair. He recounts his friendship with a man named K, their rivalry for the affections of a woman, and the resulting betrayal that culminated in the tragic death of K. The guilt and remorse over these events have haunted him ever since, leading to his self-imposed isolation.\n

"Kokoro" delves deeply into themes of loneliness, guilt, and the search for meaning in a rapidly changing society. Through the introspective and poignant narrative, Sōseki captures the essence of the human condition, making "Kokoro" a timeless and influential work in Japanese literature.', 2.99, 0.0, 4.3, 0, 10),
(5, 'Meditations', 'Marcus Auerlius', 'Penguin UK', '2006', '0140449337', '["Philosphy", "Self-help", "Autobiography"]', 433, 'English', 'pdf', '/covers/meditations.jpg', '/Meditations.pdf', 'Meditations by Marcus Aurelius is a collection of personal writings and reflections by the Roman Emperor, providing insights into Stoic philosophy and his thoughts on life, duty, and virtue. Written as a series of notes to himself, the work explores themes such as the importance of rationality, self-discipline, and the transient nature of existence. It serves as a guide to personal improvement and ethical living, emphasizing inner peace and resilience in the face of adversity. The text remains a significant source of philosophical guidance and inspiration.', 8.99, 0.99, 4.8, 0, 10),
(6, 'Atomic Habits', 'James Clear', 'Penguin Publishing Group', '2018', 'B07D23CFGR', '["Self-Help"]', 291, 'English', 'pdf', '/covers/atomic-habits.jpg', '/Atomic Habits.pdf', '"Atomic Habits" by James Clear is a self-help book that explores the science behind habit formation and provides practical strategies for building good habits and breaking bad ones. Clear argues that small changes, or "atomic habits," can lead to remarkable results over time. He introduces the concept of the "habit loop" and explains how habits are formed, maintained, and changed.\m

The book offers a comprehensive framework for habit formation, focusing on four key principles: making habits obvious, attractive, easy, and satisfying. Clear provides actionable advice on how to apply these principles to various areas of life, such as health, productivity, and relationships. He emphasizes the importance of setting clear goals, tracking progress, and creating an environment conducive to habit formation.\m

Through real-life examples, scientific research, and practical exercises, "Atomic Habits" offers readers a roadmap for transforming their habits and achieving their goals. It encourages readers to focus on continuous improvement and to harness the power of small changes to create lasting positive change in their lives.', 1.99, 0.0, 4.9, 0, 10),
(7, 'Sapiens', 'Yuval N. Harari', 'Signal Books', '2014', '0771038526', '["Non-Fiction", "Anthropology", "Science"]', 443, 'English', 'pdf', '/covers/sapiens.jpg', '/Sapiens.pdf', '"Sapiens: A Brief History of Humankind" by Yuval Noah Harari is a sweeping historical narrative that explores the origins and evolution of Homo sapiens, from the emergence of our species in Africa to the present day. Harari examines key milestones in human history, including the Cognitive Revolution, the Agricultural Revolution, the development of complex societies, and the rise of empires and civilizations.\n

The book offers a thought-provoking analysis of how humans have shaped the world around them and been shaped by it in return. Harari challenges conventional wisdom and offers fresh perspectives on topics such as the rise of religion, the spread of agriculture, and the impact of technology on society.\n

Through engaging storytelling and rigorous research, "Sapiens" invites readers to reconsider their understanding of human history and to reflect on the future of our species. The insightful commentary prompts readers to ponder questions about identity, progress, and the meaning of life in the modern world.', 9.99, 1.00, 4.7, 0, 10),
(8, '1984', 'George Orwell', 'Buccaneer Books', '1949', '0899663680', '["Fiction", "Dystopian"]', 309, 'English', 'pdf', '/covers/1984.jpg', '/1984.pdf', '1984 by George Orwell is a dystopian novel set in a totalitarian society where the government, led by the Party and its leader Big Brother, exercises complete control over every aspect of citizens&apos; lives. The story follows Winston Smith, an employee of the Party&apos;s Ministry of Truth, who becomes disillusioned with the oppressive regime and begins to rebel against it.\n

In the world of 1984, individuality is suppressed, truth is manipulated, and dissent is brutally punished. The Party employs surveillance, propaganda, and thought control to maintain its grip on power, creating a climate of fear and suspicion among the populace.\n

As Winston embarks on a journey of resistance, he forms a forbidden relationship with Julia, a fellow Party member, and begins to question the reality of the world around him. However, their rebellion against the Party comes at great personal risk, and they soon find themselves ensnared in a web of betrayal and deceit.', 7.99, 1.99, 4.5, 0, 10),
(9, 'On The Geneology of Morals', 'Freidrich Nietzsche', 'Arcturus Digital Limited', '2020', '1398806021', '["Philosophy"]', 196, 'English', 'epub', '/covers/on-the-geneology-of-morals.jpg', '/On The Geneology Of Morals.epub', 'Friedrich Nietzsche&apos;s influential book, On The Genealogy of Morality, explores the historical development of our moral concepts. Nietzsche argues that there are two main types of morality\n

Master morality: This morality is associated with the strong, noble, and powerful. People who hold this view see themselves as good and define goodness in terms of their own strength and flourishing. They see weakness as bad.\n

Slave morality: This morality originates with the weak and powerless. Resentful of the strong, they develop a morality that emphasizes pity, humility, and kindness.exclamation They define themselves as good in opposition to the cruelty of the strong.\n

Nietzsche argues that slave morality has become dominant in Western culture, leading to a decline in creativity and vitality. He criticizes Christianity and asceticism for promoting these values.\n

Here are some additional points to consider\n
Nietzsche uses the term "genealogy" metaphorically to trace the origins and development of moral concepts.\n
He criticizes traditional morality for being based on resentment rather than a healthy striving for flourishing.\n
The book is a complex and challenging work, and there is debate about how to interpret Nietzsche&apos;s ideas.', 12.95, 1.95, 4.4, 0, 10),
(10, 'Good Omens', 'Neil G., Terry P.', 'Harper Collins', '2006', '0060853980', '["Fantasy", "Comedy"]', 434, 'English', 'epub', '/covers/good-omens.jpg', '/Good Omens.epub', 'Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch by Neil Gaiman and Terry Pratchett is a brilliantly funny and wildly imaginative tale about the end of the world. When the angel Aziraphale and the demon Crowley discover that the Antichrist has been born, they form an unlikely alliance to prevent the apocalypse. Having grown quite fond of life on Earth, the two work together to sabotage the divine plan. With a cast of quirky characters, including a witch, a witch-hunter, and the Antichrist himself, this satirical romp through the supernatural world is a delightful exploration of good, evil, and everything in between. As the final judgment approaches, hilarity ensues, proving that even the most celestial of beings can have very human problems.', 9.99, 0.0, 4.6, 0, 10),
(11, 'Nightcrawling', 'Leila Mottley', 'knopf Doubleday Publishing Group', '2022', 'B09GPZ55KS', '["Fiction", "Commentary"]', 288, 'English', 'pdf', '/covers/nightcrawling.jpg', '/Nightcrawling.pdf', 'In "Nightcrawling" by Leila Mottley, readers are drawn into the harrowing and poignant world of Kiara Johnson, a young woman navigating the complexities of life in Oakland, California. Faced with relentless financial struggles and a broken family, Kiara is thrust into a world she never imagined, becoming entangled in a scandal that exposes systemic corruption and the exploitation of the vulnerable. The powerful debut novel is a searing exploration of resilience, survival, and the quest for justice in the face of overwhelming odds. With raw and lyrical prose, "Nightcrawling" shines a light on the darkest corners of society, offering a gripping and unflinching look at the human spirit and its capacity to endure.', 6.99, 0.0, 4.6, 0, 10),
(12, 'The Song Of Achillies', 'Madeline M. Miller', 'Ecco.', '2013', '00620606271', '["Mythology", "Romance"]', 415, 'English', 'pdf', '/covers/the-song-of-achillies.jpg', '/The Song Of Achillies.pdf', 'In "The Song of Achilles" by Madeline Miller, the legendary story of the Trojan War is brought to life through the eyes of Patroclus, the exiled prince who becomes the devoted companion of Achilles, the greatest warrior of his generation. Set against the backdrop of ancient Greece, this beautifully crafted novel weaves together the themes of love, honor, and destiny. As Achilles rises to fame and the shadow of war looms closer, the bond between the two men deepens into an unbreakable connection, tested by the gods and fate itself. With lyrical prose and rich, immersive storytelling, "The Song of Achilles" offers a poignant and unforgettable retelling of one of the greatest epics, celebrating the enduring power of love and the human spirit.', 16.99, 2.99, 4.8, 0, 10),
(13, 'Rich Dad Poor Dad', 'Robert T. Kiyosaki', 'Plata Publishing', '2017', '1612680194', '["Self-Help", "Business"]', 326, 'English', 'pdf', '/covers/rich-dad-poor-dad.jpg', '/Rich Dad Poor Dad.pdf', 'In "Rich Dad Poor Dad" by Robert T. Kiyosaki, readers are introduced to two influential father figures who shape the author&apos;s understanding of wealth and success. The "Poor Dad" is Kiyosaki&apos;s biological father, a highly educated man who struggles financially, while the "Rich Dad" is his best friend&apos;s father, a successful entrepreneur with a unique perspective on money. Through a series of compelling anecdotes and practical lessons, Kiyosaki contrasts their philosophies, revealing the key principles that can lead to financial independence and prosperity. This groundbreaking book challenges conventional wisdom about work and money, emphasizing the importance of financial education, investing, and creating multiple streams of income. "Rich Dad Poor Dad" has inspired millions to rethink their approach to wealth-building and take control of their financial futures.', 4.99, 0.0, 4.1, 0, 10),
(14, 'The Setting Sun', 'Osamu Dazai', 'New Directions Publishing', '1968', '0811200329', '["Fiction", "Psychological"]', 196, 'English', 'pdf', '/covers/the-setting-sun.jpg', '/The Setting Sun.pdf', 'In "The Setting Sun" by Osamu Dazai, the post-war turbulence of Japan is poignantly captured through the eyes of Kazuko, a young woman from a formerly aristocratic family now facing the stark realities of a rapidly changing society. As her family&apos;s fortunes wane, Kazuko grapples with the loss of traditional values and the search for identity and purpose in a world that seems to be crumbling around her. Dazai&apos;s haunting prose and deep psychological insight offer a compelling exploration of disillusionment, resilience, and the human condition. "The Setting Sun" is a timeless tale of transformation and survival, reflecting the broader existential crises of post-war Japan and the universal struggle between past and future.', 13.99, 0.99, 4.3, 0, 10),
(15, 'All The Pretty Horses', 'Cormac McCarthy', 'Vintage Books', '1993', '0679744398', '["Fiction", "Adventure"]', 301, 'English', 'pdf', '/covers/all-the-pretty-horses.jpg', '/All The Pretty Horses.pdf', 'In "All the Pretty Horses" by Cormac McCarthy, the American West unfolds in a rich tapestry of adventure and introspection. This acclaimed novel follows the journey of sixteen-year-old John Grady Cole, who, after the loss of his family&apos;s ranch, sets out for Mexico in search of a life unbound by modern constraints. Accompanied by his friend Lacey Rawlins, John Grady&apos;s quest leads him through a landscape as beautiful as it is brutal, where he encounters love, violence, and the harsh realities of survival. McCarthy&apos;s masterful prose and evocative storytelling illuminate the timeless themes of freedom, loyalty, and the quest for meaning. "All the Pretty Horses" is a compelling exploration of the American spirit, capturing the essence of a bygone era and the enduring allure of the open frontier.', 9.99, 3.99, 4.6, 0, 10),
(16, 'Pride And Prejudice', 'Jane Austen', 'Barnes Noble Classics', '2004', '0237525801', '["Romance", "Historical", "Commentary"]', 386, 'English', 'pdf', '/covers/pride-and-prejudice.jpg', '/Pride And Prejudice.pdf', 'In "Pride and Prejudice" by Jane Austen, the witty and independent Elizabeth Bennet navigates the complexities of love, family, and societal expectations in early 19th-century England. When the wealthy and aloof Mr. Darcy arrives in her life, Elizabeth&apos;s initial disdain for him transforms into a deep and unexpected attraction as misunderstandings and pride give way to understanding and affection. Austen&apos;s timeless novel is a brilliant exploration of the themes of love, class, and social mobility, infused with sharp humor and keen observations of human nature. "Pride and Prejudice" remains one of the most beloved works in English literature, celebrated for its enduring characters and insightful critique of society.', 15.99, 1.99, 4.9, 0, 10),
(17, 'Fahrenheit 451', 'Ray Bradbury', 'Simon & Schuster', '2013', '1451673310', '["Fiction", "Dystopian"]', 249, 'English', 'epub', '/covers/fahrenheit-451.jpg', '/Fahrenheit 451.pdf', 'In "Fahrenheit 451" by Ray Bradbury, readers are thrust into a future society where books are banned, and "firemen" burn any that are found. Guy Montag, one such fireman, lives a life of conformity and ignorance until he encounters Clarisse, a young woman who opens his eyes to the world of ideas hidden within books. As Montag begins to question the oppressive regime and his role in it, he becomes a fugitive in a society that punishes free thought and intellectualism. Bradbury&apos;s haunting and prophetic novel is a powerful exploration of censorship, the consequences of state-controlled media, and the enduring power of literature. "Fahrenheit 451" challenges readers to reflect on their own world and the importance of preserving and valuing knowledge and creativity.', 9.99, 0.99, 4.5, 0, 10),
(18, 'The Selfish Gene', 'Richard Dawkins', 'Oxford University Press', '2016', '0198788606', '["Science"]', 497, 'English', 'pdf', '/covers/the-selfish-gene.jpg', '/The Selfish Gene.pdf', 'In "The Selfish Gene" by Richard Dawkins, the renowned evolutionary biologist offers a groundbreaking perspective on the process of natural selection. Dawkins introduces the concept of the "selfish gene," proposing that genes drive evolution by prioritizing their own survival and replication. Through clear and engaging prose, Dawkins explains complex scientific ideas, illustrating how traits and behaviors that seem altruistic are actually strategies for gene survival. The book delves into topics such as kin selection, the role of genes in shaping behavior, and the intricate dance of evolutionary competition and cooperation. "The Selfish Gene" has profoundly influenced our understanding of biology and remains a seminal work in the field, challenging readers to rethink the mechanisms of life and the nature of evolutionary success.', 10.99, 2.99, 4.5, 0, 10)